root_path: ./

# aes config
use_aes: True
aes_key: "20250703qwerzxcv"
aes_iv: "20250703qwerzxcv"

# stopwords|data filter config
language: cn
set_cn_stopwords: true
additional_stopwords: []
filter_messages_setting:
  keywords_to_remove:  ['快递', '外卖', '美食', '包裹', '物流']
  keep_keywords: ['贷', '借', '金融', '信用', '好分期', '花呗', '呗', '钱']

# vectorization|embedding config
static_vec: word2vec
dynamic_vec: roberta # roberta # beg-m3 # qwen3
w2v_config: {
        "vector_size": 300,
        "window": 5,
        "min_count": 2,
        "workers": 4,
        "epochs": 10,
        "sg": 1
    }

tf_idf_config: {
        "max_features": 300,
        "ngram_range": [1, 2],
        "min_df": 2,
        "max_df": 0.95,
        "sublinear_tf": True
    }

chunk_size: 200000

